# Generated by Django 4.0.5 on 2022-06-05 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_change_email', 'Can change the user email')]},
        ),
    ]
