version: "3"

services:

  backend:
    command: python app/manage.py runserver 0:8000
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DEBUG=True

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:5050"
    env_file:
      - .env