version: "3"

services:
  rabbitmq:
    image: rabbitmq:3.10.2-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    env_file:
      - .env

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
#    environment:
#      POSTGRES_PASSWORD: "superSecretPassword"
#      POSTGRES_USER: "example_user"
#      POSTGRES_DB: "currency"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}
