# Generated by Django 4.0.2 on 2022-02-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='remove_me',
            field=models.CharField(default='', max_length=10),
        ),
    ]
