# Generated by Django 4.0.2 on 2022-02-20 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_rate_remove_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='remove_me',
        ),
    ]
