# Generated by Django 4.0.2 on 2022-03-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0004_contactus_alter_rate_created_alter_rate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
