# Generated by Django 4.0.2 on 2022-03-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_contactus_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
