version: "3"

services:

  backend:
    image: local:0.0.1
    build: .
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - "./:/code/build"
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:5050"
    env_file:
      - .env

volumes:
  db_data: {}
